version: '3'

services:

  wordpress:
    image: wordpress:5.3-php7.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=ls-7a1a8166a3f36f92ed94bce45b23fffc9f06fc75.clmq9cwqh09m.us-west-2.rds.amazonaws.com:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=dbwordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - app-network
  
  portainer:
    depends_on:
      - webserver      
    image: portainer/portainer
    restart: always
    ports:
      - "9002:9000"
      - "8000:8000"      
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
        
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email filipe@canionlabs.io --agree-tos --no-eff-email --force-renewal -d apiki.duckdns.org -d www.apiki.duckdns.org
   
volumes:
  certbot-etc:
  wordpress:
  portainer_data:        

networks:
  app-network:
    driver: bridge
